### ISSUE TITLE
support .Net framework 4.0?

### ISSUE THREAD

**Issue by retroj** [fsprojects/LSON#6]
Hello,

Any chance you could release a build of LSON that would be compatible with .Net Framework 4.0?  This library looks absolutely perfect for something in my project, but I'm stuck using an old .Net.  Thank you!

**Comment by wallymathieu** [comment]
The easiest way to do that would be to use it as a paket reference:
https://github.com/fsprojects/SyntacticVersioning/blob/master/paket.dependencies#L5 : 
```
github fsprojects/LSON LSON.fs
```
In order to use this library as a NuGet dependency you could make a pull request. The main dependency is `FParsec` for the NuGet version of this  library. So the library could be changed to match:
https://github.com/stephan-tolksdorf/fparsec/blob/master/FParsec/FParsec.fsproj#L4
```
<TargetFrameworks>net40-client;net45;netstandard1.6;portable-net45+win8+wp8+wpa81</TargetFrameworks>
```

**Comment by wallymathieu** [comment]
@retroj how did it go btw?

**Comment by retroj** [comment]
I ended up just adding LSON.fs to the project.  Since it's just a single source file, this seemed simplest.

**Comment by wallymathieu** [comment]
Sounds good
